clear;clc;
[myinfo,color]=config();

t=linspace(-pi/2,pi/2,100);
x=linspace(-1/2,1/2,100);
y=linspace(-1/4,1/4,100);
[X,Y]=meshgrid(x,y);
z1=sqrt(4.*cos(t));
z2=X.^2/4+Y.^2/16;
z3=4.*X.^2+9.*Y.^2-1;
z4=sin(X/4).*cos(4.*Y);
subplot(2,2,1);plot(t,z1)
xlabel('x');
ylabel('y');
title('曲线图');
subplot(2,2,2);mesh(X,Y,z2)
xlabel('x');
ylabel('y');
zlabel('z');
title('曲面图');
subplot(2,2,3);plot3(X,Y,z3)
xlabel('x');
ylabel('y');
zlabel('z');
title('三维曲线图');
subplot(2,2,4);contour(X,Y,z4)
xlabel('x');
ylabel('y');
title('等高线图');
shading interp
suptitle(myinfo)
